version: "3.9"

services:

  # rabbitmq:
  #   image: rabbitmq:management
  #   container_name: rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    depends_on:
      - redis
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    command: python manage.py runserver 0.0.0.0:8000
    container_name: backend
    environment:
      - SECRET_KEY=test
      - DEBUG=True

  # worker:
  #   depends_on:
  #     - redis
  #     - backend
  #     # - rabbitmq
  #   build: .
  #   container_name: celery
  #   command: celery -A core worker -l INFO
  #   volumes:
  #     - ./core:/app


  smtp4dev:
      image: rnwood/smtp4dev:v3
      restart: always
      ports:
        - '5000:80'
        - '25:25'
        - '143:143'
      volumes:
        - smtp4dev-data:/smtp4dev
      environment:
        - ServerOptions__HostName=smtp4dev
    
    
volumes:
  smtp4dev-data:
