name: Django Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup docker-compose
      run: docker-compose up -d
    - name: Flake8 and Pytest
      run: docker exec backend sh -c 'python manage.py test && pytest .'
      
